### ISSUE TITLE
Can I use this for my app and how?

### ISSUE THREAD

**Issue by rhen99** [xRuiAlves/fide-ratings-scraper#24]
Hello. I'm looking for a chess api and I stumbled upon this on [reddit](https://www.reddit.com/r/chess/comments/dflcjx/fide_ratings_api/). Is it possible to integrate this in a web app?

**Comment by xRuiAlves** [comment]
Hello! For sure :)

**Comment by xRuiAlves** [comment]
The server logic to expose the scrapping capabilities in a web server's API is present in https://github.com/xRuiAlves/fide-ratings-scraper/blob/master/src/api.js

You will need to have this running in your own VPS.

Alternatively, you can just consume the library
