### ISSUE TITLE
Did you really not include any endpoint for search queries?

### ISSUE THREAD

**Issue by aloysiuslip** [xRuiAlves/fide-ratings-scraper#3]
Surely the first thing anyone wants to do with this database is look up a name. If you're require a FIDE ID first then the utility of this is extremely limited.

**Comment by aloysiuslip** [comment]
So there should be some endpoint which is a 'search' endpoint - you enter a search string, such as `John Smith` and it returns a list of search results, complete with IDs and extra metadata that users within an app could then use to fetch their ID.

**Comment by DanijelDomazet** [comment]
> Surely the first thing anyone wants to do with this database is look up a name. If you're require a FIDE ID first then the utility of this is extremely limited.

Well, it depends... my use case (chess club members web page) is pretty much covered by this implementation. 👍
