### ISSUE TITLE
Also, people know how to set up their own express servers. You should just create a package that requests the endpoints and then returns the data.

### ISSUE THREAD

**Issue by aloysiuslip** [xRuiAlves/fide-ratings-scraper#4]

**Comment by xRuiAlves** [comment]
@aloysiuslip Thank you for your input. Could you please elaborate?

**Comment by aloysiuslip** [comment]
You've packaged this in such a way that includes a main.js with an express server. What's the point? People know how to handle requests and know how to handle errors and data outputs and so on. You're actually limiting the versatility of your package by structuring it in this way - anyone wanting to integrate this package to their app can't use it in this format, they'll have to clone it and do their own thing.
The valuable part of this is your rating.js, you should make that your index.ts and move main.js as an optional server.js that people can use *only if they need*.

**Comment by xRuiAlves** [comment]
@aloysiuslip Alright, I see what you mean.

Just some tips for you regarding generic open source contributing and feature suggesting:
- Use the title of the Issue to shortly describe the goal of the issue (adding labels to better characterize it)
- Use the body of the Issue to thoroughly explain your point of view, possibly referencing code sections, files, modules and others.

Also, just some friendly advice, maybe you could also work on the social part when you're interacting with other people, by communicating things in a clear way without being harsh and keeping a friendly tone. Feedback is always welcome, but people usually don't take it well when you are not polite.
