### ISSUE TITLE
https://lit-wildwood-98645.herokuapp.com/ not working, getting 404 

### ISSUE THREAD

**Issue by pedrosarkis** [xRuiAlves/fide-ratings-scraper#6]
Your running example it's not working

**Comment by xRuiAlves** [comment]
Hello @pedrosarkis! I'm pinging the API and getting success full responses. You can try [this endpoint](https://lit-wildwood-98645.herokuapp.com/player/1962000/info) for example.

Maybe you just happened to have the "bad luck" to catch some random heroku maintenance downtime :sweat_smile:
